name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
      uses: actions/checkout@v2
      
    - name: Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: artemtech/javahelloworld
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: artemtech
        password: ${{ secrets.DOCKER_TOKEN }}
